title: Aminah Olorunoje
theme: jekyll-theme-slate
description:  Data analyst with a strong interest in machine learning and AI. 
  Focused on using data-driven approaches to solve complex problems and deliver actionable insights. 
